### ISSUE TITLE
the better classifier for action detection

### ISSUE THREAD

**Issue by rickey-yao** [achie27/FabBits#2]
Hello, recently I read your blog and I am confused that the train set for the SVM. Can I konw that how did you get the better classifier for action detection?

**Comment by achie27** [comment]
Hey! The action scene detection pipeline uses `shot_detector.py` to find scenes & shots and then generate features for the SVM. Originally, my algorithm for grouping shots together into a scene was based on getting one representative or key frame for each shot. However, it was naive and did not take some stuff, which I have mentioned in the blog, into consideration. This, in turn, also affected the fidelity and correctness of the features extracted for action scene detection.
I got around this by representing a shot by more than one key frame (https://github.com/achie27/FabBits/blob/master/shot_detector.py#L322). Since `shot_detector.py` worked better than before, it led to a significant increase in the classifier's quality too; hence making it better.

**Comment by rickey-yao** [comment]
Thanks for your answer! Actually, when the action_scene_detector.py runs, loading the classifier.pkl to predict the features. Can I know about that what training set you used to get the classifier.pkl? Thank you!

**Comment by achie27** [comment]
I extracted all the features and shot timestamps, using `shot_detector.py`, from various movies and manually marked each shot for having action scene (1) or not (0). Then I trained an SVM with this.

**Comment by achie27** [comment]
I extracted all the features and timestamps, using shot_detector.py, from various movies and manually marked each scene for having action sequence (1) or not (0). Then I trained an SVM with this.
